import {
  User,
  DollarSign,
  ReceiptIndianRupee,
  FileText,
  Loader2,
  Mail,
  PersonStanding,
  Phone,
  CreditCard,
  Target,
  Calendar,
  Users,
  Briefcase,
  UserCheck,
  MapPin,
  Currency,
  Tag,
  Percent,
  Building,
  IdCard,
  RefreshCcw  
} from "lucide-react"

export const Icons = {
  user: User,
  users: Users,
  dollarSign: DollarSign,
  receiptIndianRupee: ReceiptIndianRupee,
  fileText: FileText,
  spinner: Loader2,
  mail: Mail,
  gender: PersonStanding,
  phone: Phone,
  creditCard: CreditCard,
  userCheck: UserCheck,
  briefcase: Briefcase,
  target: Target,
  mapPin: MapPin,
  currency: Currency,
  tag: Tag,
  percent: Percent,
  building: Building,
  reload: RefreshCcw,
  idCard: IdCard,
  calendar: Calendar
} 